#pragma config(Sensor, S3,     color,          sensorLightActive)
#pragma config(Sensor, S2,     linea,          sensorLightActive)
#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          Der,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Izq,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Gar,           tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int vMotor=30, vGarra=20, tGarra = 400;
/**
1. Agarrar la pelota
**/
motor[Gar] = 20;
waitInMilliseconds(1100);
motor[Gar] = 0;
/**
2. Girar para encontrar linea
**/
motor[Izq] = 0;
motor[Der] = -50;
waitInMilliseconds(1100);
motor[Izq] = 60;
motor[Der] = 60;
waitInMilliseconds(1000);
/** 
3. Seguir linea hasta obstaculo
**/
while(SensorValue(sonar)>15){
if(SensorValue(linea) < 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
}
/**
4. Esquivar arbol
**/
motor[Der] = -20;
motor[Izq] = -20;
waitInMilliseconds(1000);
motor[Izq] = 50;
motor[Der] = 25;
waitInMilliseconds(1300);
motor[Izq] = 25;
motor[Der] = 50;
waitInMilliseconds(2600);
/**
5. Seguir linea hasta rampa
**/
ClearTimer(T1);
while(time1[T1]<4900){
if(SensorValue(linea) < 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
}
motor[Der] = 0;
motor[Izq] = 0;
waitInMilliseconds(110);
/**
6. Subir rampa
**/ 
motor[Der] = 70;
motor[Izq] = 100;
//motor[Gar] = -vGarra;
waitInMilliseconds(1100);
motor[Der] = 0;
motor[Izq] = 0;
/**
7. Soltar bola
**/
motor[Gar] = -30;
waitInMilliseconds(1000);
motor[Gar] = 0;
//Cerrar la garra para mejor movimiento
motor[Gar] = 30;
waitInMilliseconds(1000);
motor[Gar] = 0;
/**
8. Bajar rampa
**/
motor[Der] = -40;
motor[Izq] = -40;
waitInMilliseconds(2250);
motor[Der] = 0;
motor[Izq] = 0;
 
/**
9. Esquivar alberca
**/
//Girar derecha
motor[Der] = 0;
motor[Izq] = 100;
waitInMilliseconds(500);
//Avanzar
motor[Der] = 50;
motor[Izq] = 50;
waitInMilliseconds(550);
//Girar Izquierda
motor[Der] = 100;
motor[Izq] = 0;
waitInMilliseconds(400);
//Avanzar
motor[Der] = 100;
motor[Izq] = 75;
waitInMilliseconds(2250);
stopMotor(Der);
stopMotor(Izq);
waitInMilliseconds(100);
/**
10. Buscar Bola
**/
//Girar 
motor[Izq] = 0;
motor[Der] = 25;
waitInMilliseconds(1750);
//Avanzar
motor[Izq] = 25;
waitInMilliseconds(630);
 
//Preparar la garra
motor[Gar] = -30;
waitInMilliseconds(400);
motor[Gar] = 0;
 
//Girar
motor[Izq] = 0;
motor[Der] = 25;
waitInMilliseconds(1500); 
motor[Der] = 0;
motor[Izq] = 0;
 
//Avanzar
motor[Izq] = 25;
motor[Der] = 25;
waitInMilliseconds(750);
 
//Parar
motor[Izq] = 0;
motor[Der] = 0;
 
 
/*********************************************************/
 
/**
 11. Coger la bola
**/
motor[Gar] = 30;
waitInMilliseconds(700);
motor[Gar] = 0;
/**
 12. Escoger el lado al cual dirigirse
**/
bool lado;
if(SensorValue(color) < 40){
lado = true;
} else {
lado = false;
}
motor[Der] = 0;
motor[Izq] = 0;
PlayTone(784, 10); 
waitInMilliseconds(1000);
/**
 13. Retroceder y buscar la linea
**/ 
//Retroceder
motor[Izq] = -50;
motor[Der] = -50;
waitInMilliseconds(850);
//Girar
motor[Izq] = 50;
motor[Der] = 0;
waitInMilliseconds(1000);
 
//Avanzar para buscar la linea
ClearTimer(T1);
while(time1[T1]<1000){
motor[Izq] = 50;
motor[Der] = 50;
}
/**
 14. Seguir linea curva
**/
ClearTimer(T1);
while(time1[T1]<2500){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
}
/**
 15. Saltar hueco 
**/
 motor[Izq] = 50;
 motor[Der] = 70;
 waitInMilliseconds(400);
 
/**
 16. Seguir linea recta
**/
ClearTimer(T1);
while(time1[T1]<5250){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
/**
 17. Dependiendo del color girar 
**/
if(lado == true){
/**
 17.1 Azul
**/
//Buscar curva
motor[Izq] = 50;
motor[Der] = 55;
waitInMilliseconds(750);
//Seguir curva
ClearTimer(T1);
while(time1[T1]<4250){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
} else {
/**
 17.2 Rojo
**/
//Buscar curva
motor[Izq] = 50;
motor[Der] = 40;
waitInMilliseconds(1200);
//Seguir curva
ClearTimer(T1);
while(time1[T1]<4000){
if(SensorValue(linea) < 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
}
motor[Der] = 0;
motor[Izq] = 0;
/**
 18. Dejar la bola y cerrar la garra
**/
motor[Gar] = -vGarra;
waitInMilliseconds(tGarra);
motor[Gar] = vGarra;
waitInMilliseconds(tGarra);
motor[Gar] = 0;
/**
19. Retroceder para poder girar
**/
if(lado==true){
/**
 19.1 Azul
**/
//reversa
motor[Der] = -30;
motor[Izq] = -30;
waitInMilliseconds(1700);
//Girar
motor[Der] = 50;
motor[Izq] = 0;
waitInMilliseconds(1000);
//Seguir curva
ClearTimer(T1);
while(time1[T1]<2000){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
//Avanzar para coger linea
motor[Der] = 30;
motor[Izq] = 30;
waitInMilliseconds(500);
while(time1[T1]<8500){
if(SensorValue(linea) < 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
motor[Der] = 40;
motor[Izq] = 30;
waitInMilliseconds(800);
}else{
/**
 19.2 Rojo
**/
//reversa
motor[Der] = -30;
motor[Izq] = -30;
waitInMilliseconds(1700);
//Girar
motor[Der] = 0;
motor[Izq] = 50;
waitInMilliseconds(1350);
//Seguir curva
ClearTimer(T1);
while(time1[T1]<2000){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
//Avanzar para coger linea
motor[Der] = 30;
motor[Izq] = 30;
waitInMilliseconds(500);
while(time1[T1]<8000){
if(SensorValue(linea) > 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
motor[Der] = 40;
motor[Izq] = 30;
waitInMilliseconds(800);
}
/**
20. Seguir linea final
**/
ClearTimer(T1);
while(time1[T1]<13500){
if(SensorValue(linea) < 35){
motor[Der] = 40;
motor[Izq] = 15;
} else {
motor[Der] = 15;
motor[Izq] = 40;
}
} 
motor[Der] = 0;
motor[Izq] = 0;
PlayTone(784, 10); 
waitInMilliseconds(1000);
}
